Feature/update landing page
vora/design-assistant pull request #5
Opened 2021-10-06 15:52 UTC by Philip-Loeffler

2021-10-07 17:34 UTC, ONeill45 commented on src/App.js
> +        <h1>RAI Certification: Fair Landing</h1>
Change to RAI Assessment

2021-10-07 17:34 UTC, ONeill45 commented on src/App.js
> +        height: '52vh',
I'd scale the height down. Try perhaps 25-30vh

2021-10-07 17:34 UTC, ONeill45 commented on src/Components/Assessment.js
> +  const leftArrow = (img.src = '../img/leftArrow.png');
Pull the arrows and users from material ui icons instead of adding them to public.

2021-10-07 17:34 UTC, ONeill45 commented on src/Components/Assessment.js
> +    setActiveStep((prevActiveStep) => prevActiveStep - 1);
add logic to wrap around back to the first slide when hitting next on the last slide

2021-10-07 17:34 UTC, ONeill45 commented on src/Components/Assessment.js
> +              {activeStep < 5 ? (
Move slide out to a component and import

2021-10-07 17:34 UTC, ONeill45 commented on src/Components/ProjectCard.js
> +                <img src="/img/refresh.png" alt="refresh" />
swap out all three images on the buttons for material ui equivalents

2021-10-07 17:34 UTC, ONeill45 commented on src/Components/ProjectCard.js
> +      <Card className={classes.root}>
Up the `elevation` proper to add some box shadow

2021-10-08 17:33 UTC, Philip-Loeffler commented on src/Components/Assessment.js
> +    setActiveStep((prevActiveStep) => prevActiveStep - 1);
Per new design, I didn't update this because Bhawana has the arrow disappearing when its on its last item

2021-10-12 16:45 UTC, ONeill45 requested changes

2021-10-12 16:45 UTC, ONeill45 commented on src/App.js
> +          ‌way.‌Committed‌ ‌to‌ ‌making‌ ‌responsible‌ ‌AI‌ ‌systems,‌ ‌we’ve‌
Missing a space before 'Committed'

2021-10-12 16:45 UTC, ONeill45 commented on src/Components/Assessment.js
> +  return (
Seeing some extra whitespace between the header and the assessment title:
![Screen Shot 2021-10-12 at 12 17 05 PM](https://user-images.githubusercontent.com/13375042/136994531-222d2526-2e12-4451-8d3e-a24263112757.png)

2021-10-12 16:45 UTC, ONeill45 commented on src/Components/Assessment.js
> +import KeyboardArrowDown from '@material-ui/icons/KeyboardArrowDown';
Combine these icon imports: `import { KeyboardArrowDown, KeyboardArrowUp } from '@material-ui/icons'`

2021-10-12 16:45 UTC, ONeill45 commented on src/Components/AssessmentSlider.js
> +import KeyboardArrowLeft from '@material-ui/icons/KeyboardArrowLeft';
combine imports

2021-10-12 16:45 UTC, ONeill45 commented on src/Components/AssessmentSlider.js
> +            <KeyboardArrowLeft
Make both the left and right arrows have `cursor: pointer`

2021-10-12 16:45 UTC, ONeill45 commented on src/Components/ProjectCardStyle.js
> +    fontSize: 24,
Up this to 36 and add a little font weight

2021-10-12 16:45 UTC, ONeill45 commented on src/Components/ProjectCard.js
> +          <div>Updated by: {updatedBy}</div>
Fade this slightly and lower size to 16px

2021-10-12 16:45 UTC, ONeill45 commented on src/Components/ProjectCard.js
> +              label={projectStatus ? 'Deployment' : 'Design'}
Status should be all caps. When status is 'View Reports' change color and underline per the design

2021-10-12 16:45 UTC, ONeill45 commented on src/Components/ProjectCard.js
> +          <div className={classes.statusRow}>
status row needs a bit more padding to align with the other text on the card: 
![image](https://user-images.githubusercontent.com/13375042/136995860-7d1f4d58-075d-471e-99a3-2afc04c65b16.png)

2021-10-12 16:45 UTC, ONeill45 commented on src/views/UserSubmissions.js
> +                  statusTitle={'Pending Review - LOD 1'}
Don't need brackets for string props on components

2021-10-12 16:47 UTC, ONeill45 commented
Need to update the app to use Exo 2 for the font. Add the link in `public/index.html`:![Screen Shot 2021-10-12 at 12 42 31 PM](https://user-images.githubusercontent.com/13375042/136996961-ff62354f-1e0e-439c-95da-d5c375ab4118.png)


Then wrap a ThemeProvider around `Router.js` line in our old `rai-collab` repo:


![image](https://user-images.githubusercontent.com/13375042/136997056-a0d08f76-790f-4be7-874b-7890a1e3a71a.png)

2021-10-28 20:06 UTC, ONeill45 requested changes

2021-10-28 20:06 UTC, ONeill45 commented on src/App.js
> +import Button from '@material-ui/core/Button';
import as `import { Button, Box } from '@material-ui/core'` instead

2021-10-28 20:06 UTC, ONeill45 commented on src/Components/Assessment.js
> +  return (
Still seeing extra whitespace here

2021-10-28 20:06 UTC, ONeill45 commented on src/Components/AssessmentGrid.js
> +import Pagination from '@material-ui/lab/Pagination';
Missing `@material-ui/lab` from the package.json. Breaking on start

2021-10-28 20:06 UTC, ONeill45 commented on src/Components/ProjectCard.js
> +import React from 'react';
Is this file still needed with the changes to the landing page?

2021-10-28 20:06 UTC, ONeill45 commented
Delete the `package-lock.json` file

2021-11-01 13:21 UTC, Philip-Loeffler commented on src/App.js
> +import Button from '@material-ui/core/Button';
removed button. Actually wasnt being used in this file at all.

2021-11-02 14:46 UTC, closed without merging